### ISSUE TITLE
dynamic libraries prevent using prebuilt clients

### ISSUE THREAD

**Issue by tthoma24** [macathena/moira#1]
For example:

Teddy-Thomas-Mac-VM:bin localadmin$ ./stanley tthoma24
dyld: Library not loaded: /Users/leee/Downloads/moira-el_capitan/lib/libmrclient.0.dylib
  Referenced from: /Users/localadmin/src/moira/bin/./stanley
  Reason: image not found
Abort trap: 6

**Comment by leee** [comment]
Known issue, my fault. Requesting for it to be made available via homebrew-core - [watch this pull request](https://github.com/Homebrew/homebrew-core/pull/5702) for it's status.

Once that's taken care of, I can deal with the fixes needed on the [pull request](https://github.com/caskroom/homebrew-cask/pull/25282) for our packaged moira to be made available via homebrew-cask (that is, along with the requested changes in the code review, `hesiod` needs to be made a requirement alongside `krb5`).

**Comment by leee** [comment]
`hesiod` is now available via `homebrew-core`.

Changes submitted to the packaged moira, albeit on an older version, but I'll take it.

More prodding will have to be done to see what can be done about having a current moira from upstream.

**Comment by leee** [comment]
Closing this issue in favor of https://github.com/macathena/macathena/issues/1
